spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123Mudar
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create